id: P008054
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W4CZ1107
  title: 'གསུང་འབུམ། ཚེ་དབང་རྣམ་རྒྱལ། '
  author: ''
  volumes:
    b9bc306939a04c47942ff6ca77cd9eee:
      image_group_id: I1KG16813
      title: Volume 1 of gsung 'bum/_tshe dbang rnam rgyal/
      volume_number: 1
      total_pages: 634
      base_file: v001.txt
