id: P008054
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ1107
  title: 'གསུང་འབུམ། ཚེ་དབང་རྣམ་རྒྱལ། '
  author: ''
  volumes:
    1b518aa805154c119b72f8274e0635dc:
      image_group_id: I1KG16813
      title: ''
      volume_number: 1
      total_pages: 634
ebook_metadata:
  title: 'གསུང་འབུམ། ཚེ་དབང་རྣམ་རྒྱལ། '
  author: ''
  sku: P008054
  cover: cover.jpg
  layers:
  - pagination
